name: secp256k1-haskell
version: 0.4.0
synopsis: Bindings for secp256k1
description: Sign and verify signatures using the secp256k1 library.
category: Crypto
author: Jean-Pierre Rupp
maintainer: jprupp@protonmail.ch
copyright: (c) 2017 Jean-Pierre Rupp
license: MIT
license-file: LICENSE
github: haskoin/secp256k1-haskell.git
homepage: http://github.com/haskoin/secp256k1-haskell#readme
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.8 && <5
  - base16-bytestring >= 0.1.1.6 && < 1.0
  - bytestring
  - cereal
  - entropy
  - deepseq
  - hashable
  - QuickCheck
  - string-conversions
  - unliftio
library:
  source-dirs: src
  generated-exposed-modules:
    - Paths_secp256k1_haskell
  pkg-config-dependencies:
    - libsecp256k1
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - secp256k1-haskell
      - monad-par
      - mtl
      - HUnit
